NAV_ITEMS = [
    ("assets/icons/dashboard.png", "Dashboard", "dashboard"),
    ("assets/icons/class.png", "Class", "class"),
    ("assets/icons/store.png", "Store", "store"),
    ("assets/icons/warehouse.png", "Warehouse", "warehouse"),
    ("assets/icons/party.png", "Party", "party"),
    ("assets/icons/inventory.png", "Inventory", "inventory"),
    ("assets/icons/stock.png", "Stock", "stock"),
    ("assets/icons/sales.png", "Sales", "sales"),
    ("assets/icons/purchase.png", "Purchase", "purchase"),
    ("assets/icons/accounts.png", "Accounts", "accounts"),
    ("assets/icons/pos.png", "POS Billing", "pos"),
    ("assets/icons/report.png", "Report", "report"),
    ("assets/icons/attendance.png", "Attendance", "attendance"),
    ("assets/icons/settings.png", "Settings", "settings"),
]